import 'package:flutter/material.dart';
import 'package:movie_app/modules/booking/model/showtime.dart';
import 'package:movie_app/modules/booking/model/ticket.dart';
import 'package:movie_app/modules/movie/model/tmdb_movie.dart';
import 'package:movie_app/services/booking/booking_service.dart';
import 'package:movie_app/services/payment/vnpay_service.dart';
import 'package:webview_flutter/webview_flutter.dart';
import 'package:firebase_auth/firebase_auth.dart';

class PaymentWebviewScreen extends StatefulWidget {
  final TMDBMovie movie;
  final Showtime showtime;
  final String cinemaName;
  final List<String> selectedSeats;
  final double totalAmount;

  const PaymentWebviewScreen({
    Key? key,
    required this.movie,
    required this.showtime,
    required this.cinemaName,
    required this.selectedSeats,
    required this.totalAmount,
  }) : super(key: key);

  @override
  State<PaymentWebviewScreen> createState() => _PaymentWebviewScreenState();
}

class _PaymentWebviewScreenState extends State<PaymentWebviewScreen> {
  late final WebViewController _controller;
  final VNPayService _vnPayService = VNPayService();
  final BookingService _bookingService = BookingService();
  bool _isProcessing = false;

  @override
  void initState() {
    super.initState();
    final orderId = 'ORDER_${DateTime.now().millisecondsSinceEpoch}';
    final paymentUrl = _vnPayService.createPaymentUrl(
      orderId: orderId,
      amount: widget.totalAmount,
      orderInfo: 'Thanh toan ve xem phim ${widget.movie.title}',
    );

    _controller = WebViewController()
      ..setJavaScriptMode(JavaScriptMode.unrestricted)
      ..setNavigationDelegate(
        NavigationDelegate(
          onNavigationRequest: (request) {
            if (request.url.startsWith(VNPayService.returnUrl)) {
              _handlePaymentResult(request.url);
              return NavigationDecision.prevent;
            }
            return NavigationDecision.navigate;
          },
        ),
      )
      ..loadRequest(Uri.parse(paymentUrl));
  }

  Future<void> _handlePaymentResult(String url) async {
    if (_isProcessing) return;
    setState(() => _isProcessing = true);

    final uri = Uri.parse(url);
    final params = uri.queryParameters;

    // Check vnp_ResponseCode (00 is success)
    if (params['vnp_ResponseCode'] == '00') {
      await _completeBooking();
    } else {
      if (mounted) {
        ScaffoldMessenger.of(context).showSnackBar(
          const SnackBar(
            content: Text('Payment failed or cancelled'),
            backgroundColor: Colors.red,
          ),
        );
        Navigator.pop(context);
      }
    }
  }

  Future<void> _completeBooking() async {
    try {
      final user = FirebaseAuth.instance.currentUser;
      if (user == null) return;

      final ticket = Ticket(
        id: '', // Will be generated by Firestore add
        userId: user.uid,
        showtimeId: widget.showtime.id,
        movieId: widget.movie.id,
        movieTitle: widget.movie.title,
        cinemaName: widget.cinemaName,
        startTime: widget.showtime.startTime,
        seats: widget.selectedSeats,
        totalAmount: widget.totalAmount,
        status: 'paid',
        createdAt: DateTime.now(),
      );

      await _bookingService.createBooking(ticket);

      if (mounted) {
        _showSuccessDialog();
      }
    } catch (e) {
      if (mounted) {
        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(
            content: Text('Error creating booking: $e'),
            backgroundColor: Colors.red,
          ),
        );
        Navigator.pop(context);
      }
    }
  }

  void _showSuccessDialog() {
    showDialog(
      context: context,
      barrierDismissible: false,
      builder: (context) => AlertDialog(
        backgroundColor: Colors.grey[900],
        title: const Icon(Icons.check_circle, color: Colors.green, size: 60),
        content: const Text(
          'Booking Successful!\nYour tickets are ready.',
          textAlign: TextAlign.center,
          style: TextStyle(color: Colors.white),
        ),
        actions: [
          Center(
            child: ElevatedButton(
              onPressed: () {
                Navigator.of(context).popUntil((route) => route.isFirst);
              },
              style: ElevatedButton.styleFrom(
                backgroundColor: const Color(0xFFFF6B35),
              ),
              child: const Text(
                'Back to Home',
                style: TextStyle(color: Colors.white),
              ),
            ),
          ),
        ],
      ),
    );
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('VNPay Payment'),
        backgroundColor: const Color(0xFF005BAA), // VNPay Blue
      ),
      body: Stack(
        children: [
          WebViewWidget(controller: _controller),
          if (_isProcessing)
            const Center(
              child: CircularProgressIndicator(color: Color(0xFFFF6B35)),
            ),
        ],
      ),
    );
  }
}
