// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAeR0tndJo2x4ZZCFGCdCXuAQmb0Qyg-Qo',
    appId: '1:839831003421:web:6249318b51fef99988c1f4',
    messagingSenderId: '839831003421',
    projectId: 'movie-6b322',
    authDomain: 'movie-6b322.firebaseapp.com',
    storageBucket: 'movie-6b322.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBw3TdNMFKWuZJWJ2nte5eA98GouPcL1R4',
    appId: '1:839831003421:android:eecc6484dcf0fdd288c1f4',
    messagingSenderId: '839831003421',
    projectId: 'movie-6b322',
    storageBucket: 'movie-6b322.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCKpLo9C-YfCg_QJrsdr2epo5f9Qrxd5NQ',
    appId: '1:839831003421:ios:92ebfd2ccb6e2b2088c1f4',
    messagingSenderId: '839831003421',
    projectId: 'movie-6b322',
    storageBucket: 'movie-6b322.firebasestorage.app',
    iosBundleId: 'com.example.movieApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCKpLo9C-YfCg_QJrsdr2epo5f9Qrxd5NQ',
    appId: '1:839831003421:ios:92ebfd2ccb6e2b2088c1f4',
    messagingSenderId: '839831003421',
    projectId: 'movie-6b322',
    storageBucket: 'movie-6b322.firebasestorage.app',
    iosBundleId: 'com.example.movieApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAeR0tndJo2x4ZZCFGCdCXuAQmb0Qyg-Qo',
    appId: '1:839831003421:web:f1244914c5e38b2c88c1f4',
    messagingSenderId: '839831003421',
    projectId: 'movie-6b322',
    authDomain: 'movie-6b322.firebaseapp.com',
    storageBucket: 'movie-6b322.firebasestorage.app',
  );
}
